dist: xenial
addons:
  chrome: stable
language: java
jdk:
  - openjdk8
before_install:
  - sudo mkdir /AwsClient
  - sleep 3
  - sudo chown -R travis:travis /AwsClient
before_script:
  - cd CodeFactory
  - platform_version=$(cat CodeFactory/pom.xml | grep prompto.version\> | cut -d'>' -f 2 | cut -d'<' -f 1)
  - mvn dependency:get -Dartifact=org.prompto:AwsClient:${platform_version}
  - AwsClientPrefix=${HOME}/.m2/repository/org/prompto/AwsClient/${platform_version}/AwsClient-${platform_version}
  - mvn dependency:copy-dependencies -f ${AwsClientPrefix}.pom -DoutputDirectory=/AwsClient
  - cp ${AwsClientPrefix}.jar /AwsClient/
script:
  - mvn install -B -V -q # -e -X -DskipTests=true
  
