dist: xenial
addons:
  chrome: stable
language: java
jdk:
  - openjdk8
before_install:
  - sudo mkdir /AwsClient
  - sleep 3
  - sudo chown -R travis:travis /AwsClient
before_script:
  - platform_version=$(cat CodeFactory/pom.xml | grep prompto.version\> | cut -d'>' -f 2 | cut -d'<' -f 1)
  - mvn dependency:get -Dartifact=org.prompto:AwsClient:${platform-version}
  - echo ~/.m2/repository/org/prompto/AwsClient/${platform-version}/AwsClient-${platform-version} >> AwsClient-prefix.txt
  - mvn dependency:copy-dependencies -f $(cat AwsClient-prefix.txt).pom -DoutputDirectory=/AwsClient
  - cp $(cat AwsClient-prefix.txt).jar /AwsClient/
  - cd CodeFactory
script:
  - mvn install -B -V -q # -e -X -DskipTests=true
  
