version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11.0-browsers
    steps:
      - checkout
      - run:
          name: Install Mongo CLI
          command: |
            sudo apt-get install gnupg &&
            wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add - &&
            echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list &&
            sudo apt-get update &&
            sudo apt-get install -y mongodb-org-tools=4.4.11
      - run:
          name: Install AWS Client
          command: >-
            sudo mkdir /AwsClient &&
            sleep 3 && 
            sudo chown -R circleci:circleci /AwsClient &&
            cd CodeFactory &&
            platform_version=$(cat CodeFactory/pom.xml | grep prompto.version\> | cut -d'>' -f 2 | cut -d'<' -f 1) &&
            mvn dependency:get -Dartifact=org.prompto:AwsClient:${platform_version} &&
            AwsClientPrefix=${HOME}/.m2/repository/org/prompto/AwsClient/${platform_version}/AwsClient-${platform_version} &&
            mvn dependency:copy-dependencies -e -f ${AwsClientPrefix}.pom -DoutputDirectory=/AwsClient && 
            cp ${AwsClientPrefix}.jar /AwsClient/
      - run:
          name: Build
          command: >-
            cd CodeFactory &&
            mvn -B -q -DskipTests clean package
      - run:
          name: Test
          command: >-
            cd CodeFactory &&
            mvn -B -q test

workflows:
  regular:
    jobs:
      - build-and-test
